
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.0.2.10
  cors_allowed_origins:
    - !secret home_assistant_url
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  #ssl_profile: intermediate

recorder:
  db_url: !secret db_location
  exclude:
    entities:
      - sensor.rockrobo_map
    entity_globs:
      - sensor.glances*
      - sensor.galaxynote10*
      - sensor.router_iot*
    domains:
      - mobile_app
  purge_keep_days: 30
  commit_interval: 5

# Text to speech
tts:
  - platform: google_translate

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
    mode: hourly



browser_mod:
  devices:
    d82da74e_093bb3cc: 
      name: galaxytabs
    a0b8cb9f_03e5cf0b:
      name: galaxytaba
    0cf28301_70560337:
      name: galaxytabs6
    02b9eed9_b7405785:
      name: sdsa_pc
    4c680749_cb73bb22:
      name: kbk_notebook
# var:
#   people_home:
#     initial_value: on
#     icon: mdi:home-account
#   bedtime_announced:
#     initial_value: off
#     icon: mdi:sleep

zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_8130075A-if00-port0
  network_key: !secret zwave_network_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  
discovery:

media_player:
  - platform: soundtouch
    host: 10.0.2.160
    port: 8090
    name: Dining
  - platform: soundtouch
    host: 10.0.2.161
    port: 8090
    name: Kitchen
  - platform: soundtouch
    host: 10.0.2.162
    port: 8090
    name: Living Room



ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_events_id
    client_secret: !secret alexa_events_secret
    filter:
      include_domains:
        - climate
        - media_player
        - scene
        - script
        - switch
        - light
        - vacuum
    entity_config:
      media_player.dining:
        display_categories: SPEAKER
      media_player.living_room:
        display_categories: SPEAKER
      media_player.kitchen:
        display_categories: SPEAKER

vacuum:
  - platform: mqtt



mobile_app:

# badnest:
#   issue_token: !secret badnest_issue_token
#   cookie: !secret badnest_cookie
#   region: us
  
# climate:
#   - platform: badnest
#     scan_interval: 10

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

apcupsd:
  host: a722577e-apcupsd

ddwrt:
  devices:
    - name: router_iot
      host: 10.0.2.1
      username: !secret router_iot_username
      password: !secret router_iot_password
      ssl: true
      verify_ssl: false
      sensor:
        - clk_freq
        - cpu_temp
        - ip_connections
        - load_average1
        - load_average5
        - load_average15
        - uptime
        - voltage
        - wl_channel
        - wl_count
        - wl_quality
        - wl_rate
        - wl_xmit

zha_map:
  
switch: !include switches.yaml

light: !include lights.yaml

camera:
  - platform: mjpeg
    mjpeg_url: http://10.0.2.121:2971/camera/stream
    name: Galaxy Tab S Camera
  - platform: mjpeg
    mjpeg_url: http://10.0.2.124:2971/camera/stream
    name: Galaxy Tab S6 Camera
  - platform: mjpeg
    mjpeg_url: http://10.0.2.122:2971/camera/stream
    name: Galaxy Tab A Camera




sensor:
  - platform: nws_alerts
    zone_id: !secret nws_zone

#   - platform: systemmonitor
#     resources:
#       - type: disk_use_percent
#         arg: /
#       - type: memory_use_percent
#       - type: processor_use
#       - type: throughput_network_in
#         arg: enp3s0
#       - type: throughput_network_out
#         arg: enp3s0

  # - platform: openweathermap
  #   api_key: !secret openweathermap_apikey
  #   forecast: false
  #   monitored_conditions:
  #     - clouds
  #     - weather_code
  #     - wind_speed
  #     - humidity
  #     - rain
  #     - snow

  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data_parsed"
    name: rockrobo_map
    value_template: 'OK'
    scan_interval: 5

  - platform: template
    sensors:
      # theater_peripherals_watts:
      #   friendly_name_template: "{{ states.switch.vesync_switch.theater_peripherals}} Current Consumption"
      #   value_template: '{{ states.switch.theater_peripherals.attributes["current_power_w"] | float }}'
      #   unit_of_measurement: 'W'
      # office_peripherals_watts:
      #   friendly_name_template: "{{ states.switch.vesync_switch.office_peripherals}} Current Consumption"
      #   value_template: '{{ states.switch.office_peripherals.attributes["current_power_w"] | float }}'
      #   unit_of_measurement: 'W'
      # living_room_monitor_watts:
      #   friendly_name_template: "{{ states.switch.vesync_switch.living_room_monitor}} Current Consumption"
      #   value_template: '{{ states.switch.living_room_monitor.attributes["current_power_w"] | float }}'
      #   unit_of_measurement: 'W'
      # spotify_source:
      #   friendly_name: "Spotify Source"
      #   value_template: "{{ state_attr('media_player.spotify', 'source') }}"
      hallway_humidity:
        friendly_name: "Hallway Thermostat Humidity"
        value_template: '{{ state_attr("climate.hallway_thermostat", "current_humidity") }}'
        unit_of_measurement: '%'
      ups_watts:
        friendly_name: "UPS Current Consumption"
        value_template: '{{ (states("sensor.ups_load") | float / 100 * 330) | round (2) }}'
        unit_of_measurement: 'W'
      router_iot_wl_quality_numeric:
        value_template: '{{ states(''sensor.router_iot_wl_quality'')[0:2] | int }}'
        unit_of_measurement: '%'
      home_humidity:
        friendly_name_template: "Humidity"
        value_template: '{{ state_attr("weather.home", "humidity") }}'
        unit_of_measurement: '%'
      home_pressure:
        friendly_name_template: "Pressure"
        value_template: '{{ state_attr("weather.home", "pressure") }}'
        unit_of_measurement: 'hPa'
      home_wind_speed:
        friendly_name_template: "Wind Speed"
        value_template: '{{ state_attr("weather.home", "wind_speed") }}'
        unit_of_measurement: 'km/h'
      home_visibility:
        friendly_name_template: "Visibility"
        value_template: '{{ state_attr("weather.home", "visibility") }}'
        unit_of_measurement: 'km'

  - platform: mqtt
    state_topic: "wallpanel/galaxytaba/sensor/battery"
    name: "Galaxy Tab A Battery Level"
    unit_of_measurement: "%"
    value_template: '{{ value_json.value }}'

  - platform: mqtt
    state_topic: "wallpanel/galaxytabs/sensor/light"
    name: "Galaxy Tab S Light Level"
    unit_of_measurement: "lx"
    value_template: '{{ value_json.value }}'
  - platform: mqtt
    state_topic: "wallpanel/galaxytabs/sensor/magneticField"
    name: "Galaxy Tab S Magnetic Field"
    unit_of_measurement: "uT"
    value_template: '{{ value_json.value }}'
  - platform: mqtt
    state_topic: "wallpanel/galaxytabs/sensor/battery"
    name: "Galaxy Tab S Battery Level"
    unit_of_measurement: "%"
    value_template: '{{ value_json.value }}'

  - platform: mqtt
    state_topic: "wallpanel/galaxytabs6/sensor/light"
    name: "Galaxy Tab S6 Light Level"
    unit_of_measurement: "lx"
    value_template: '{{ value_json.value }}'
  - platform: mqtt
    state_topic: "wallpanel/galaxytabs6/sensor/battery"
    name: "Galaxy Tab S6 Battery Level"
    unit_of_measurement: "%"
    value_template: '{{ value_json.value }}'

  - platform: apcupsd
    resources:
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - maxlinev
      - minlinev
      - outputv

binary_sensor:
  - platform: mqtt
    state_topic: "wallpanel/galaxytabs/sensor/motion"
    name: "Galaxy Tab S Motion"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion 
  - platform: mqtt
    state_topic: "wallpanel/galaxytaba/sensor/motion"
    name: "Galaxy Tab A Motion"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion 
  - platform: mqtt
    state_topic: "wallpanel/galaxytabs6/sensor/motion"
    name: "Galaxy Tab S6 Motion"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion 



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

panel_custom: !include panel_custom.yaml

