- platform: template
  lights:
    ir_strips:
      unique_id: light.ir_strips
      turn_on:
        data:
          device: 'RGB LED'
          command: 'PowerOn'
        entity_id: remote.harmony_hub
        service: remote.send_command
      turn_off:
        - data:
            device: 'RGB LED'
            command: 'PowerOn'
          entity_id: remote.harmony_hub
          service: remote.send_command
        - data:
            device: 'RGB LED'
            command: 'PowerOff'
          entity_id: remote.harmony_hub
          service: remote.send_command
      set_level:
        - data:
            device: 'RGB LED'
            command: 'Brighter 2'
            num_repeats: 6
          entity_id: remote.harmony_hub
          service: remote.send_command
        - condition: template
          value_template: '{{ brightness < 255 - 32 }}'
        - data_template:
            device: 'RGB LED'
            command: 'Darker 2'
            num_repeats: '{{ (((255 - brightness) / 32) - 1) | int }}'
          entity_id: remote.harmony_hub
          service: remote.send_command
      set_white_value:
        data:
          device: 'RGB LED'
          command: 'White Color'
        entity_id: remote.harmony_hub
        service: remote.send_command
      set_color:
        data_template:
          device: 'RGB LED'
          command: '{{ [''ColorRed'', ''ColorOrange'', ''ColorYellow'', ''ColorGreen'',
            ''ColorGreen'', ''ColorTurquoise'', ''ColorAqua'',  ''ColorLightBlue'', ''ColorBlue'', ''ColorPurple'',
            ''ColorPink'', ''ColorPink''] [((h + 15) % 360 / 30) | int] }}'
        entity_id: remote.harmony_hub
        service: remote.send_command
    kitchen:
      unique_id: light.kitchen
      level_template: "{{ state_attr('light.kitchen_overhead', 'brightness') }}"
      value_template: "{{ is_state('light.kitchen_overhead', 'on') or is_state('light.kitchen_strips', 'on') or is_state('light.kitchen_spotlight', 'on') }}"
      color_template: "{{ state_attr('light.kitchen_overhead', 'hs_color') }}"
      turn_on:
        - data_template:
            hs_color:
            - '{{ (180 - (atan(state_attr(''sun.sun'', ''elevation'') / (180 - state_attr(''sun.sun'',
              ''azimuth''))) / pi * 180 + (90 * (1 - ( ( (180 - state_attr(''sun.sun'',
              ''azimuth'')) | abs) /  (180 - state_attr(''sun.sun'', ''azimuth'')) ) ) )
              ) / 360 * 180) % 360 }}'
            - 80
          entity_id: light.kitchen_strips
          service: light.turn_on
        - condition: state
          entity_id: automation.kitchen_motion_stop_after_bedtime
          state: 'off'
        - data_template:
            hs_color:
            - '{{ (120 - (atan(state_attr(''sun.sun'', ''elevation'') / (180 - state_attr(''sun.sun'',
              ''azimuth''))) / pi * 180 + (90 * (1 - ( ( (180 - state_attr(''sun.sun'',
              ''azimuth'')) | abs) /  (180 - state_attr(''sun.sun'', ''azimuth'')) ) ) )
              ) / 360 * 180) % 360}}'
            - 20
          entity_id: light.kitchen_overhead
          service: light.turn_on
        - entity_id: light.kitchen_spotlight
          service: light.turn_on
        - condition: state
          entity_id: light.dining
          state: 'off'
        - data_template:
            hs_color:
            - '{{ (180 - (atan(state_attr(''sun.sun'', ''elevation'') / (180 - state_attr(''sun.sun'',
              ''azimuth''))) / pi * 180 + (90 * (1 - ( ( (180 - state_attr(''sun.sun'',
              ''azimuth'')) | abs) /  (180 - state_attr(''sun.sun'', ''azimuth'')) ) ) )
              ) / 360 * 180) % 360 }}'
            - 50
          entity_id: light.dining
          service: light.turn_on

      turn_off:
        - entity_id: light.kitchen_spotlight
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.kitchen_right
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.kitchen_mid_right
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.kitchen_mid_left
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.kitchen_left
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.kitchen_forward
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.kitchen_strips
          service: light.turn_off

      set_level:
        - data_template:
            brightness: '{{ brightness }}'
          entity_id: light.kitchen_overhead
          service: light.turn_on
        - data_template:
            brightness: '{{ brightness }}'
          entity_id: light.kitchen_strips
          service: light.turn_on
        - data_template:
            brightness: '{{ brightness }}'
          entity_id: light.kitchen_spotlight
          service: light.turn_on
      set_white_value:
        - data_template:
            white_value: '{{ white_value }}'
          entity_id: light.kitchen_overhead
          service: light.turn_on
        - data_template:
            white_value: '{{ white_value * 0.6 }}'
          entity_id: light.kitchen_strips
          service: light.turn_on
      set_color:
        - data_template:
            hs_color: '[ {{ h }}, {{ s * 0.6 }} ]'
          entity_id: light.kitchen_overhead
          service: light.turn_on
        - data_template:
            hs_color: '[ {{ (h + 30) % 360 }}, {{ s }} ]'
          entity_id: light.kitchen_strips
          service: light.turn_on

    office:
      unique_id: light.office
      level_template: "{{ ((state_attr('light.office_lamp', 'brightness') | int + state_attr('light.office_strips', 'brightness') | int ) / 2) | int }}"
      value_template: "{{ is_state('light.office_strips', 'on') or is_state('light.office_lamp', 'on') }}"
      color_template: "{{ state_attr('light.office_strips', 'hs_color') }}"
      turn_on:
        - data_template:
            hs_color:
            - '{{ (180 - (atan(state_attr(''sun.sun'', ''elevation'') / (180 - state_attr(''sun.sun'',
              ''azimuth''))) / pi * 180 + (90 * (1 - ( ( (180 - state_attr(''sun.sun'',
              ''azimuth'')) | abs) /  (180 - state_attr(''sun.sun'', ''azimuth'')) ) ) )
              ) / 360 * 180) % 360 }}'
            - 80
          entity_id: light.office_strips
          service: light.turn_on
        - entity_id: light.office_lamp
          service: light.turn_on

      turn_off:
        - entity_id: light.office_strips
          service: light.turn_off
        - delay: 00:00:01
        - entity_id: light.office_lamp
          service: light.turn_off

      set_level:
        - data_template:
            brightness: '{{ brightness }}'
          entity_id: light.office_strips
          service: light.turn_on
        - data_template:
            brightness: '{{ brightness }}'
          entity_id: light.office_spotlight
          service: light.turn_on
      set_white_value:
        data_template:
          white_value: '{{ white_value }}'
        entity_id: light.office_strips
        service: light.turn_on
      set_color:
        data_template:
          hs_color: '[ {{ h }}, {{ s }}  ]'
        entity_id: light.office_strips
        service: light.turn_on